### ISSUE TITLE
Pin Connections?

### ISSUE THREAD

**Issue by Abhesheksh** [MrSyabro/mfrc522_component#1]
Hello, what is the pin to pin connection here? Can you please elaborate. 

Best Wishes

**Comment by MrSyabro** [comment]
> what is the pin to pin connection here?

Hello, the connection is standard for ESP8266.

### On ESP8266 (NodeMCU):

- `MOSI` -> `GPIO13` (NodeMCU D7)
- `MISO` -> `GPIO12` (NodeMCU D6)
- `CLK` -> `GPIO14` (NodeMCU D5)
- `CS` -> `GPIO15` (NodeMCU D8)

**Comment by Abhesheksh** [comment]
Большое спасибо
